spring:
    application:
        name: backend-jpa
    datasource:
        #url: jdbc:mysql://mysql:3306/mydatabase
        #username: myuser
        #password: mypassword
        #driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:h2:mem:mydatabase
        driver-class-name: org.h2.Driver
        username: sa
        password:
    h2:
        console:
            enabled: true
            settings:
                web-allow-others: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                #dialect: org.hibernate.dialect.MySQL8Dialect
                dialect: org.hibernate.dialect.H2Dialect
